Added some small grammar corrections.
woohoolabs/harmony pull request #18
Opened 2016-10-01 00:18 UTC by AndreeaEne

2016-10-01 19:00 UTC, yarwest requested changes
There is still bad grammar in a number of places

2016-10-01 19:33 UTC, kocsismate commented
Hi Andrea,

I just have accepted another PR for the read me so now, your have some conflicts. :S Could you please resolve them? Sorry for the inconvenience.

2016-10-01 19:40 UTC, kocsismate requested changes
Thanks for your time! I like your changes very much :)

2016-10-01 19:40 UTC, kocsismate commented on README.md
> +Our aim was to create an invisible, easily extensible, ande extremely flexible framework for your
typo: ande

2016-10-01 19:40 UTC, kocsismate commented on README.md
> +functionality that's is minimally needed. It doesn't have any capabilities which are not truly required. That's why Harmony
another small typo: "that's is"

2016-10-02 21:03 UTC, AndreeaEne commented
Done! :)

2016-10-03 14:22 UTC, kocsismate commented
Thank you! Now you should resolve the conflicts because I can't merge your changes automatically.

2016-10-07 11:08 UTC, AndreeaEne commented
Probably because I changed some of the conflicted words as well.

2016-10-10 12:54 UTC, closed without merging